# Generated by Django 4.0 on 2023-02-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentdata',
            new_name='student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
